
USE DB_Payments;

CREATE TABLE CreditCards (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	num VARCHAR(45) NOT NULL,
	account_id INT NOT NULL,
	FOREIGN KEY (account_id) REFERENCES BankAccounts(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);