
USE DB_Payments;

CREATE TABLE Users (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(25) NOT NULL,
	password CHAR(45) NOT NULL,
	role_id INT NOT NULL,
	FOREIGN KEY (role_id) REFERENCES User_roles(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);