
USE DB_Payments;

CREATE TABLE Payments (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	num VARCHAR(45) NOT NULL,
	credit_card_id INT NOT NULL,
	payment_amount NUMERIC(9,6) NOT NULL DEFAULT 0,
	payment_purpose VARCHAR(65),
	FOREIGN KEY (credit_card_id) REFERENCES CreditCards(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);